### PR TITLE
Add support for new languages: French #1 #5

### PR DESCRIPTION
**Pull request by pada57**
following my comment from last november [HTBox#1] 
Support for french [HTBox#5]
i started a bit refactoring for languages, i will do another PR to have better languages support

### CODE REVIEW

**Comment by toolboc** [comment]
@pada57, the refactors for obtaining CultureInfo and the LanguageConstants are very nice, and should make it much easier to add new languages.  Looks like we have some minor conflicts that need to be resolved, once those are fixed I will take the code for a test spin and merge if there are no issues encountered.

**Comment by pada57** [comment]
Ok thanks. Do you want me to resolve them?

**Comment by toolboc** [comment]
@pada57, preferably I'd like you to resolve them so we can have a couple eyes on the overall changes.  Also, I'm curious if you require this change https://github.com/HTBox/EmergencyServicesBot/commit/f811882aa578aa11b2abe3a73b65e09dff111875 as I recall it was necessary to enable interaction with the GA release of the QA Maker service.  It may not be required today, but it certainly used to be.

**Comment by pada57** [comment]
Let me check tomorrow, not sure anymore if this is needed. I will revert if not, thanks

**Comment by pada57** [comment]
@toolboc i reverted my change for header.

**Comment by toolboc** [comment]
@pada57,  I’m curious if you found that header change to be necessary.  It looks like we still have a few conflicts in RootDialog.cs that need to be resolved before merging is possible.  If you are able to address them, I should have time to review the full set of changes later today.

**Comment by pada57** [comment]
@toolboc  should be fine now. It is just i use gitkraken and it was messing merge as i shuffled lines from original file, so i had now to solve it manually.
to answer your question it was i had issue with local bot simulator at the beginning to connect. I found that i had to update following nuget package:

`  <package id="Microsoft.Net.Compilers" version="2.10.0" targetFramework="net46" developmentDependency="true" />`

so authorization was a left over from my attempts :-)

**Comment by toolboc** [comment]
@pada57, we are almost ready for acceptance, just one more thing.  It looks like your last commit https://github.com/HTBox/EmergencyServicesBot/pull/15/commits/61f4262bf090b3ab8c02e827906bd0a16b058af8 breaks operation with the GA release of QnA maker.  I have published your changes with that fix reverted to demonstrate that everything is working properly without it @ https://emergencyservicesbot-test.azurewebsites.net/ 

image

Once you make the revert to https://github.com/HTBox/EmergencyServicesBot/pull/15/commits/61f4262bf090b3ab8c02e827906bd0a16b058a , we will move ahead with merging the PR.

**Comment by pada57** [comment]
@toolboc i changed since the uri part was present already in web.config file. Fine for me, maybe config file not uptodate "/**knowledgebases**/"?

`<add key="QnAendpoint" value="https://westus.api.cognitive.microsoft.com/qnamaker/v2.0/knowledgebases/"/>`

**Comment by toolboc** [comment]
@pada57, my main line of thinking was going by the current documentation, we suggest to copy the `host` value upon deploying the QnA service, and to avoid confusion, expect the user to copy that value as-is without appending "/knowledgebases/".  

For example, upon creating a QnA service, the user will see the following:

image

Any knowledgebases that reference the "https://westus.api.cognitive.microsoft.com/qnamaker/v2.0/knowledgebases/" url endpoint, were tied to the QnA Maker preview.  The new GA service requires that the user deploy to a custom app service now which explains why the above `host` value is "https://emergencyservicesbot-test-qna.azurewebsites.net/qnamaker".  Since this value will be different for every user, and is required to be copied, we could either call out the need to append "/knowledgebases" in the documentation, or avoid that issue by providing it in code and expect the user to copy/paste the `host` value as-is.

I'm open to suggestions here, but the line of thinking is to reduce points of failure and make it easy for anyone to follow the guide to get up and running quickly and with the least amount of effort.

**Comment by pada57** [comment]
@toolboc indeed it makes sense. Should we remove from web.config default value ?

**Comment by toolboc** [comment]
@pada57, that's an interesting suggestion which points to a bigger issue.  

Above all, this project should ensure that the documentation is appropriate with the latest QnA changes (i.e. preview to GA) and that a new user can successfully replicate the bot given the information currently provided, with as little confusion as possible. 

Previously in preview, the default value "https://westus.api.cognitive.microsoft.com/qnamaker/v2.0/knowledgebases/"  was the same for everyone, but that is no longer the case.  Of course, we can simply overwrite whatever is there, but maybe it would make sense to remove it like we do with the other application settings, as this could be seen as confusing.   

Perhaps this could be part of a larger issue for overhauling documentation to conform to what's in GA today?

**Comment by toolboc** [comment]
By the way, thank you for the PR!!!!  This is excellent work that opens up the application to new users and will make it much easier to add new languages going forward!

**Comment by pada57** [comment]
@toolboc thanks for your message. I see improvements we can make which i will try to do before end of month. 

Concerning your previous point i think i agree we could remove url like for other settings

Happy coding

**Pull request merged**
